# project config
server :
  port : 8080
  servlet:
    session:
      timeout: 9999m

spring:
  datasource:
    url: jdbc:mariadb://52.78.112.142:3306/autotrade
    driver-class-name: org.mariadb.jdbc.Driver
    username: autotrade
    password: autotrade
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  file:
    name: ../logs/auto_trade.log     # 로깅 파일 위치
    max-history: 7                 # 로그 파일 삭제 주기
    max-size: 70MB                  # 로그 파일 하나당 최대 파일 사이즈
